### ISSUE TITLE
Unable to integrate gpars + gradle + intellij idea

### ISSUE THREAD

**Issue by arnoid** [GPars/GPars#27]
Hi.

I'm trying to follow instructions to integrate gpars into intellij idea + gradle.
Unfortunatelly idea is unable to see any compile dependency.
Meanwhile it is possible to build project from CL.

i do have the following dependencies:
```
compile 'org.codehaus.jsr166-mirror:jsr166y:1.7.0'
compile 'org.codehaus.gpars:gpars:1.2.1'
```

But idea highlights the `import groovyx.gpars.actor.Actors` as groovyx package as not available.

All the websites/stackoverflow answers provide links to codehaus.org which seems to be down.

So i'm asking for guides

**Comment by pditommaso** [comment]
Have you refreshed your Gradle project?

https://www.jetbrains.com/idea/help/synchronizing-changes-in-gradle-project-and-intellij-idea-project.html


p

**Comment by arnoid** [comment]
Yep.

Also, i've tried restarting idea, rebuilding from CL, rebuilding from idea in different conbinations

@pditommaso if you have working idea project template, can you provide it?

p.s. here is my build script
```
group 'org.xcape'
version '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'groovy'

dependencies {
    compile localGroovy()
}

sourceCompatibility = 1.5

repositories {
    jcenter()
    mavenLocal()
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir "src/main/java"
        }
        groovy {
            srcDir "src/main/groovy"
        }
        resources {
            srcDir "src/main/resources"
        }
    }
    test {
        java {
            srcDir "src/test/java"
        }
        groovy {
            srcDir "src/test/groovy"
        }
        resources {
            srcDir "src/test/resources"
            srcDir "../resources"
        }
    }
}

dependencies {
    compile 'org.grails:grails:2.2.5'
    compile 'org.grails:grails-core:2.2.5'

//Added all the deps because of despair
    compile "org.codehaus.gpars:gpars:1.2.1"
    compile 'org.codehaus.jsr166-mirror:jsr166y:1.7.0'
    compile "org.multiverse:multiverse-core:0.7.0"
    compile "org.codehaus.jcsp:jcsp:1.1-rc5"
    compile "org.codehaus.groovy:groovy-all:1.7.0"
    compile "org.jboss.netty:netty:3.2.9.Final"

    compile "com.badlogicgames.gdx:gdx:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-box2d:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-bullet:$gdxVersion"
    compile "com.badlogicgames.box2dlights:box2dlights:$box2DLightsVersion"
    compile "com.badlogicgames.ashley:ashley:$ashleyVersion"
    compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    compile "com.badlogicgames.gdx:gdx-ai:$aiVersion"
    compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"

    compile "com.underwaterapps.overlap2druntime:overlap2d-runtime-libgdx:0.1.0"

    compile "com.kotcrab.vis:vis-ui:0.8.1"
    compile "com.kotcrab.vis:vis-runtime:0.2.1"

    compile "net.dermetfan.libgdx-utils:libgdx-utils:0.13.1"
    compile "net.dermetfan.libgdx-utils:libgdx-utils-box2d:0.13.1"
}
```

**Comment by pditommaso** [comment]
You may try to have a look at [this](https://github.com/nextflow-io/nextflow/blob/master/build.gradle). 

However this is not a GPars issue. It's a problem either with your gradle build file or IntelliJ. I would suggest to isolate the problem with a smaller script and using the gradle command line.

**Comment by arnoid** [comment]
Sorry for bothering.

I've copy-pasted the org.codehouse dependencies from the @pditommaso example and it start working in another submodule. So i think it is purely idea issues.

Closing this ticket
