### ISSUE TITLE
GPars fails to build on JDK9

### ISSUE THREAD

**Issue by russel** [GPars/GPars#29]
GPars master builds fine and passes it's tests using JDK8. Using JDK9 there are 42 errors during compilation, all of which seem to be due to changes in the type parameter system and type matching of generics.

**Comment by benignbala** [comment]
I have got it to build on JDK9 - https://github.com/benignbala/GPars/tree/jdk9 But there a lot of tests failing. I didn't have to do any changes on top my jdk8 branch for the build to go through.

**Comment by russel** [comment]
The changes needed for GPars to work on JDK8 as opposed to working on JDK7 are not yet complete. The tests have not been amended. I have been dithering about whether to preserve the GPars 1.x API in GPars 2.x. I am rapidly coming to the conclusion "No". This means removing all the API (and hence tests) that would be realized by using JDK8 Streams – where currently extra166e types are used.  Groovy code should use Streams directly and not use an API that introduces barriers to efficient execution. If these changes are made on JDK9 then they should "Just Work"™ on JDK8. I propose we do not create a distinct jdk9 branch as yet, there should be no features in GPars 2.x that require JDK9: i.e. GPars does not as yet make use of the module system. So let us for now focus on the jdk8 branch, but ensure this issue is dealt with. Then we can introduce modularization on a jdk9 branch which may lead to a GPars 3.x.

**Comment by benignbala** [comment]
Agree - In which case, we can probably remove most of eachParallel/everyParallel/* kind of methods since there are methods like anyMatch and allMatch natively on the Streams.

I had sent in a pull request for getting the JDK8 branch to compile. I have just replaced parallel array with parallel stream there in most cases to get it working. So, please do let me know if we have to (may be selectively) remove them all ? Thanks

**Comment by russel** [comment]
Let's ship all JDK8 thoughts to Issue #37 .

**Comment by russel** [comment]
Closing this issue since so much has changed, as stated it is not useful. A new issue needs raising.
