### ISSUE TITLE
Remove all codehaus.org links

### ISSUE THREAD

**Issue by sirinath** [GPars/GPars#34]
Can you remove all the codehaus.org links. Especially the one at the top project description.

**Comment by russel** [comment]
Which links are you thinking of?

**Comment by jwagenleitner** [comment]
The description of the project on the main [Github page](https://github.com/GPars/GPars) still references the codehaus link.

>The GPars concurrency and parallelism framework for the JVM http://gpars.codehaus.org

**Comment by russel** [comment]
OK, fixed that one. Any others?

**Comment by jwagenleitner** [comment]
Started to list other pages but it turned out to be several so thought it would be easier to submit a PR #35.

**Comment by jnorthr** [comment]
have removed codehaus references from website documentation, though some may exists in the GPars core.

**Comment by russel** [comment]
Pull request #44 references this issue. All documentation related Codehaus references are gone, just need to check the codebase itself then we can close this issue.

**Comment by russel** [comment]
I believe this is no longer an issue.

**Comment by jnorthr** [comment]
agreed.
