### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Jarema** [GPars/GPars#39]
1. Link on the top of the project ( http://gpars.website ) redirects to http://gparsdocs.de.a9sapp.eu/ which returns `404 Not Found: Requested route ('gparsdocs.de.a9sapp.eu') does not exist.`
2. Link to installer (`http://www.gpars.org/download/`) returns `403 forbidden`
3. All links in download section return `404 not found`.

**Comment by jnorthr** [comment]
That URL is obsolete as of Jan.2017. We have a temporary cache of our doc.s here: 
http://gpars.aws.ie.a9sapp.eu/
Pls advise any any of your issues remain in the temp.cache as we can fix those quick-ish ;-)

**Comment by vl3** [comment]
There are links for older versions than 1.0? I have as a dependency of a project that i'm working on.

**Comment by jnorthr** [comment]
Have taken a look at our available downloads and can find this https://github.com/GPars/Website/tree/master/src/main/webapp/downloads as earliest. Maven central has older versions here: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.codehaus.gpars%22%20AND%20a%3A%22gpars%22 but have not worked with these before so cannot say if they will work for you.
Thx
Jim

**Comment by jnorthr** [comment]
gpars.website no longer exists, so we can close this issue.

**Comment by jnorthr** [comment]
thank you.
