### ISSUE TITLE
Fix implementation of GParsPoolUtil class

### ISSUE THREAD

**Issue by wololock** [GPars/GPars#49]
Fix `GParsPoolUtil` class to satisfy all failing tests. Use Java Stream API for all parallel operations in combination with ForkJoinPool so thread pool size can be controlled with `withPool(x)` method.

![przechwycenie obrazu ekranu_2017-07-08_14-38-16](https://user-images.githubusercontent.com/1258405/27985436-40c78198-63eb-11e7-8cde-854d13a6202e.png)

@russel, please assign this task to me, I've already started working on it.

This task is related to #48

**Comment by wololock** [comment]
@russel I have one question regarding `eachWithIndexParallel` method. Here is a test case that fails:

```
    public void testEachWithIndex() {
        groovyx.gpars.GParsPool.withPool(5) {
            final AtomicInteger result = new AtomicInteger(0)
            GParsPoolUtil.eachWithIndexParallel([1, 2, 3, 4, 5], { element, int index -> result.addAndGet(element * index) })
            assert 40 == result
        }
    }
```

I just noticed that implementation of this method in `1.2.1` is a blocking one, so such test case does not fail:

![przechwycenie obrazu ekranu_2017-07-08_15-23-05](https://user-images.githubusercontent.com/1258405/27985736-607ca896-63f1-11e7-9e23-de7bac379ff9.png)

I've implemented `eachWithIndexParallel` using ForkJoinPool and Java Stream API, here is what the code looks like:

```
    public static <T> Collection<T> eachWithIndexParallel(final Collection<T> collection, final Closure cl) {
        final AtomicInteger counter = new AtomicInteger(0);
        retrievePool().submit(() ->
                collection.parallelStream()
                        .forEach(it -> cl.call(it, counter.getAndIncrement()))
        );
        return collection;
    }
```

The main difference between old implementation and the new one is that the new one is non-blocking, so the test case I've pasted above fails - assertion happens before computation is finished. Now the main question is: should I make `eachWithIndexParallel` a blocking method or should I update the test case so it waits until all computations are over?

**Comment by wololock** [comment]
Another interesting case. This time `testSeededReduce` test case

```
    public void testSeededReduce() {
        groovyx.gpars.GParsPool.withPool(5) {
            assert 15 == [1, 2, 3, 4, 5].injectParallel(0) { a, b -> a + b }
            assert 25 == [1, 2, 3, 4, 5].injectParallel(10) { a, b -> a + b }
            assert 'abc' == 'abc'.injectParallel('') { a, b -> a + b }
            assert 'abcd' == 'abc'.injectParallel('d') { a, b -> a + b }
        }
    }
```

Second assertion fails when I run it in parallel. 

```
Assertion failed: 

assert 25 == [1, 2, 3, 4, 5].injectParallel(10) { a, b -> a + b }
          |                  |
          false              65
```

This assertion works fine with GPars 1.2.1 and it proves it runs in a single sequention: start with 10 and pick any number, let's say 3. In next iteration pick another number (let's say 1) and add it to 13 (previously calculated) etc. When run in parallel it behaves differently: all 5 (in this example) threads start with 10 and they pick a number from list (every thread picks different number), so we have pairs like: 10+3, 10+4, 10+1, 10+5 and 10+2. These values are used in next parallel calculation. Below you can find what it looks like:

```
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 3
[ForkJoinPool-1-worker-4] seed = 10, a = 10, b = 4
[ForkJoinPool-1-worker-2] seed = 10, a = 10, b = 1
[ForkJoinPool-1-worker-5] seed = 10, a = 10, b = 5
[ForkJoinPool-1-worker-3] seed = 10, a = 10, b = 2
[ForkJoinPool-1-worker-5] seed = 10, a = 14, b = 15
[ForkJoinPool-1-worker-3] seed = 10, a = 11, b = 12
[ForkJoinPool-1-worker-5] seed = 10, a = 13, b = 29
[ForkJoinPool-1-worker-5] seed = 10, a = 23, b = 42
```
I have experimented with different number of threads, final value is always 65 in this case. And there is one very weird situation - when I set `withPool(1)` and only one thread is doing calculation, result is still 65:

```
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 3
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 5
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 4
[ForkJoinPool-1-worker-1] seed = 10, a = 14, b = 15
[ForkJoinPool-1-worker-1] seed = 10, a = 13, b = 29
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 2
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 1
[ForkJoinPool-1-worker-1] seed = 10, a = 11, b = 12
[ForkJoinPool-1-worker-1] seed = 10, a = 23, b = 42
```

But if I switch from `collection.parallelStream()` to `collection.stream()` then assertion with number 25 is satisfied (calculation is run on a single thread though):

```
[ForkJoinPool-1-worker-1] seed = 10, a = 10, b = 1
[ForkJoinPool-1-worker-1] seed = 10, a = 11, b = 2
[ForkJoinPool-1-worker-1] seed = 10, a = 13, b = 3
[ForkJoinPool-1-worker-1] seed = 10, a = 16, b = 4
[ForkJoinPool-1-worker-1] seed = 10, a = 20, b = 5
```

Here is the implementation I'm playing around with:

```
    public static <T> T injectParallel(final Collection<T> collection, final T seed, final Closure cl) throws ExecutionException, InterruptedException {
        //return collection.parallelStream().reduce(seed, new ClosureReducer<T>(cl));
        System.out.println("injectParallel(final Collection<T> collection, final T seed, final Closure cl)");
        return retrievePool().submit(() ->
                collection.parallelStream().reduce(seed, (a,b) -> {
                    System.out.println("[" + Thread.currentThread().getName() + "] seed = " + seed + ", a = " + a + ", b = " + b);
                    return (T) cl.call(a,b);
                })
        ).get();
    }
```

@russel do you have an idea what is desired behavior in this case? From one point of view threads should not wait until others are done with calculation, but in this case `withPool(1)` should behave like a non-parallel stream and as we can see - it does not.

**Comment by russel** [comment]
I wonder if we could get @vaclav to take a quick look at this to give a high level view? Then we can get on with finalising these codes and tests.

**Comment by russel** [comment]
Overall, I think the ParallelArray based API has to be blocking calls. This implies that if we reimplement that API using Stream we have to preserve the blocking nature of the calls. Given that people can use Streams directly and get non-blocking that way, this seems reasonable.
 
I had been tempted just to remove all the API that was backed by ParallelArray and require people to use Streams for all data parallel work. If we "rescue" the old API then keeping the blocking nature seems right – preserve the API as was.

**Comment by wololock** [comment]
I do agree on blocking nature here, especially that people can always use Java Stream API for non-blocking as you've mentioned. The only questionable thing is that `injectParallel` example with initial seed - parallel stream computation ends with different result then the sequential one. I will dig deeper into that. @vaclav, do you have any suggestions?

I should finish reimplementing `GParsPoolUtil` class tomorrow and will create PR for a code review.

**Comment by wololock** [comment]
@russel @vaclav I've run into weird situation after implementing `eachWithIndexParallel` method using `Stream.forEachOrdered` method. I've explained it in details in this short video - https://www.youtube.com/watch?v=ExWPGDz-QLw&feature=youtu.be

PS: I've checked what the current (1.2.1) implementation of `eachWithIndexParallel` does and it behaves as expected in both tests - order is guaranteed and every element is picked by a separate thread for computation.

**Comment by wololock** [comment]
Ok, my previous implementation was not correct - it didn't make sense to submit task and wait for the result. Instead submitting tasks and joining results in the end does the right trick. Here is what the correct method looks like:

```
    public static <T> Collection<T> eachWithIndexParallel(final Collection<T> collection, final Closure cl) {
        final AtomicInteger counter = new AtomicInteger(0);
        final List<ForkJoinTask> tasks = new LinkedList<>();
        final ForkJoinPool pool = retrievePool();

        collection.stream()
                .forEachOrdered(it -> {
                    int index = counter.getAndIncrement();
                    tasks.add(pool.submit(() -> cl.call(it, index)));
                });
        tasks.forEach(ForkJoinTask::join);
        return collection;
    }
```
